Repository Dev-JoseRonaldo/real-time-udp-chat, pull requests merged in 2024-03, with the labels that each got.

#24 Refactor: standardize packages and increase utils
  counter.py
  segunda_entrega/src/client.py
  segunda_entrega/src/server.py
  segunda_entrega/src/utils/constants.py
  segunda_entrega/src/utils/convert_txt.py
  segunda_entrega/src/utils/create_fragment.py
  segunda_entrega/src/utils/send_packet.py
  segunda_entrega/src/utils/update_dict_file_counter.py
Labels: feat, refactor, high priority

#25 Feat/add checksum
  counter.py
  segunda_entrega/README.md
  segunda_entrega/data/client/.gitkeep
  segunda_entrega/data/server/.gitkeep
  segunda_entrega/src/client.py
  segunda_entrega/src/server.py
  segunda_entrega/src/utils/__init__.py
  segunda_entrega/src/utils/checksum.py
  segunda_entrega/src/utils/constants.py
  segunda_entrega/src/utils/convert_txt.py
  segunda_entrega/src/utils/create_fragment.py
  segunda_entrega/src/utils/get_current_time_and_date.py
  segunda_entrega/src/utils/print_commands.py
  segunda_entrega/src/utils/send_packet.py
  segunda_entrega/src/utils/update_dict_file_counter.py
Labels: feat

#26 feat: add 3 way handshake
  segunda_entrega/src/client.py
  segunda_entrega/src/server.py
  segunda_entrega/src/utils/constants.py
  segunda_entrega/src/utils/send_packet.py
Labels: feat

#27 feat: add folder management
  segunda_entrega/src/client.py
  segunda_entrega/src/server.py
  segunda_entrega/src/utils/convert_txt.py
  segunda_entrega/src/utils/folder_management.py
Labels: feat

#28 doc: readme update
  README.md
  segunda_entrega/README.md
  segunda_entrega/src/client.py
  segunda_entrega/src/server.py
  segunda_entrega/src/utils/__init__.py
  segunda_entrega/src/utils/constants.py
  segunda_entrega/src/utils/convert_txt.py
  segunda_entrega/src/utils/create_fragment.py
Labels: docs

#29 Refactor: debug
  segunda_entrega/src/client.py
  segunda_entrega/src/server.py
  segunda_entrega/src/utils/update_dict_file_counter.py
Labels: fix
